"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 15:08:02.753222
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_defs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('searchable', sa.Boolean(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('case_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('counters',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_id', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('drawing_ids', sa.JSON(), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawing_no', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=False),
    sa.Column('current_revision_id', sa.Integer(), nullable=True),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drawings_drawing_no'), ['drawing_no'], unique=False)

    op.create_table('master_materials',
    sa.Column('material', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('density_kg_m3', sa.String(length=20), nullable=False),
    sa.Column('price_per_kg', sa.String(length=20), nullable=False),
    sa.Column('waste_factor', sa.String(length=20), nullable=False),
    sa.Column('charge_scope', sa.String(length=20), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('material')
    )
    op.create_table('master_pricing_policy',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('master_processes',
    sa.Column('process_code', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('calculation_type', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('charge_scope', sa.String(length=20), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('process_code')
    )
    op.create_table('master_surface_treatments',
    sa.Column('treatment_code', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('unit_price', sa.String(length=20), nullable=False),
    sa.Column('charge_scope', sa.String(length=20), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('treatment_code')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('specialties', sa.Text(), nullable=False),
    sa.Column('price_records', sa.Text(), nullable=False),
    sa.Column('avg_lead_days', sa.Float(), nullable=True),
    sa.Column('deal_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('customers', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('staff', sa.String(length=80), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('lost_reason', sa.String(length=40), nullable=False),
    sa.Column('competitor_price', sa.Integer(), nullable=True),
    sa.Column('lost_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(), nullable=False),
    sa.Column('first_issued_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['case_statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('drawing_categories',
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drawing_id', 'category_id')
    )
    op.create_table('drawing_memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drawing_memos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drawing_memos_drawing_id'), ['drawing_id'], unique=False)

    op.create_table('drawing_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.String(length=20), nullable=False),
    sa.Column('pdf_file_id', sa.String(length=40), nullable=False),
    sa.Column('pdf_name', sa.String(length=160), nullable=False),
    sa.Column('shape_file_id', sa.String(length=40), nullable=False),
    sa.Column('shape_name', sa.String(length=160), nullable=False),
    sa.Column('shape_kind', sa.String(length=10), nullable=False),
    sa.Column('thickness_mm', sa.Float(), nullable=True),
    sa.Column('material', sa.String(length=80), nullable=False),
    sa.Column('surface_treatment', sa.String(length=80), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('analysis_job_id', sa.String(length=40), nullable=False),
    sa.Column('reading', sa.JSON(), nullable=True),
    sa.Column('reading_job_id', sa.String(length=40), nullable=False),
    sa.Column('max_dimension_mm', sa.Float(), nullable=True),
    sa.Column('pdf_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drawing_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drawing_revisions_drawing_id'), ['drawing_id'], unique=False)

    op.create_table('case_status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=40), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_status_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_status_log_case_id'), ['case_id'], unique=False)

    op.create_table('drawing_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['drawing_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drawing_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drawing_notes_revision_id'), ['revision_id'], unique=False)

    op.create_table('past_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_no', sa.String(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=False),
    sa.Column('drawing_no', sa.String(length=80), nullable=False),
    sa.Column('revision', sa.String(length=20), nullable=False),
    sa.Column('part_name', sa.String(length=160), nullable=False),
    sa.Column('material_text', sa.String(length=80), nullable=False),
    sa.Column('material_code', sa.String(length=80), nullable=False),
    sa.Column('material_family', sa.String(length=20), nullable=False),
    sa.Column('thickness', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('finish_text', sa.String(length=80), nullable=False),
    sa.Column('finish_code', sa.String(length=80), nullable=False),
    sa.Column('processes_text', sa.Text(), nullable=False),
    sa.Column('processes', sa.JSON(), nullable=False),
    sa.Column('rush', sa.Boolean(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('staff', sa.String(length=80), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('cut', sa.Float(), nullable=True),
    sa.Column('holes', sa.Integer(), nullable=True),
    sa.Column('bends', sa.Integer(), nullable=True),
    sa.Column('flat_size', sa.String(length=40), nullable=False),
    sa.Column('shape_class', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('original', sa.JSON(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('drawing_id', sa.Integer(), nullable=True),
    sa.Column('lost_reason', sa.String(length=40), nullable=False),
    sa.Column('answer_days', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_no', 'date', 'customer', name='uq_past_quote')
    )
    with op.batch_alter_table('past_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_past_quotes_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_past_quotes_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_past_quotes_drawing_id'), ['drawing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_past_quotes_quote_no'), ['quote_no'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('reading', sa.JSON(), nullable=True),
    sa.Column('job_id', sa.String(length=40), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('chat', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['drawing_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_drawing_id'), ['drawing_id'], unique=False)

    op.create_table('issued_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('issued_by', sa.String(length=80), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=False),
    sa.Column('part_name', sa.String(length=160), nullable=False),
    sa.Column('drawing_no', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('issued_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issued_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issued_documents_quote_id'), ['quote_id'], unique=False)

    op.create_table('quote_edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('total_before', sa.Integer(), nullable=True),
    sa.Column('total_after', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_edit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_edit_log_quote_id'), ['quote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_edit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_edit_log_quote_id'))

    op.drop_table('quote_edit_log')
    with op.batch_alter_table('issued_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issued_documents_quote_id'))
        batch_op.drop_index(batch_op.f('ix_issued_documents_case_id'))

    op.drop_table('issued_documents')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_drawing_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_case_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('past_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_past_quotes_quote_no'))
        batch_op.drop_index(batch_op.f('ix_past_quotes_drawing_id'))
        batch_op.drop_index(batch_op.f('ix_past_quotes_date'))
        batch_op.drop_index(batch_op.f('ix_past_quotes_case_id'))

    op.drop_table('past_quotes')
    with op.batch_alter_table('drawing_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawing_notes_revision_id'))

    op.drop_table('drawing_notes')
    with op.batch_alter_table('case_status_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_status_log_case_id'))

    op.drop_table('case_status_log')
    with op.batch_alter_table('drawing_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawing_revisions_drawing_id'))

    op.drop_table('drawing_revisions')
    with op.batch_alter_table('drawing_memos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawing_memos_drawing_id'))

    op.drop_table('drawing_memos')
    op.drop_table('drawing_categories')
    op.drop_table('cases')
    op.drop_table('templates')
    op.drop_table('staff')
    op.drop_table('partners')
    op.drop_table('master_surface_treatments')
    op.drop_table('master_processes')
    op.drop_table('master_pricing_policy')
    op.drop_table('master_materials')
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawings_drawing_no'))

    op.drop_table('drawings')
    op.drop_table('documents')
    op.drop_table('counters')
    op.drop_table('company')
    op.drop_table('categories')
    op.drop_table('case_statuses')
    op.drop_table('attribute_defs')
    # ### end Alembic commands ###
